appkallawaya/urls.py
from django.conf.urls import url
from django.urls import path, re_path

import appkallawaya
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import handler400, handler500


urlpatterns = [
    path('', views.home),
    path('login/', LoginView.as_view(template_name='kallawaya/login.html')),
    path('logout/', LogoutView.as_view(template_name='kallawaya/logout.html')),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    url(r'^profile/(?P<pk>\d+)/', views.profile, name='user_picked'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('plants/', views.list_Plant, name='plants'),
    path('testHome/', views.testHome, name='testHome'),
    path('contact/', views.contact, name='contact'),
    path('testInit/', views.testInit, name='testInit'),
    url(r'^testInit/(?P<pk>\d+)/', views.testInit, name='testInit_picked'),
    path('herbario/', views.herbario, name='herbario'),
    url(r'^herbario/(?P<pk>\d+)/', views.herbario, name='herbario_picked'),
    path('herbario2/', views.herbario2, name='herbario2'),
    url(r'^herbario2/(?P<pk>\d+)/', views.herbario2, name='herbario2_picked')
]

djangokallawaya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from djangokallawaya import views

app_name="appkallawaya"
urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    url(r'^kallawaya/', include(('appkallawaya.urls', 'appkallawaya'), namespace='appkallawaya'))
]
    #url('kallawaya/', include('appkallawaya.urls', namespace='appkallawaya')),

appkallawaya/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
class Plant(models.Model):
    name = models.CharField(max_length=100, default='')
    description = models.CharField(max_length=1500, default='')
    cura = models.CharField(max_length=1500, default='')

    def __str__(self):
        return "Planta: {0}".format(self.name)


class Molestia(models.Model):
    name = models.CharField(max_length=100, default='')
    herb = models.ForeignKey(Plant, on_delete=models.CASCADE)

    def __str__(self):
        return "Molestia: {0} y la planta es: {1}".format(self.name, self.herb.name)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    phone = models.IntegerField(default=0)


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)


class Post(models.Model):
    post = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

appkallawaya/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from appkallawaya.models import Post


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )
        
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email_name = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name'
        )


class HomeFormInit(forms.Form):
    example = forms.CharField(widget=forms.Textarea(), required=True)

appkallawaya/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from appkallawaya.forms import RegistrationForm, EditProfileForm, HomeFormInit
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .models import Plant, Molestia
from django.views.generic import TemplateView
from appkallawaya.models import Post

from urllib.parse import quote

from django.template import Context, Engine, loader
from django.views.defaults import page_not_found

ERROR_404_TEMPLATE_NAME = 'kallawaya/error404.html'
ERROR_500_TEMPLATE_NAME = 'kallawaya/error500.html'


# Create your views here.


def home(request):
    return render(request, 'kallawaya/home.html')


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/kallawaya/login')
        else:
            form = RegistrationForm()
            args = {'form': form}
            return render(request, 'kallawaya/register.html', args)
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'kallawaya/register.html', args)


def profile(request, pk=None):
    if request.user.is_authenticated:
        if pk:
            user = User.objects.get(pk=pk)
        else:
            user = request.user
        args = {'user': user}
        return render(request, 'kallawaya/profile.html', args)
    else:
        return render(request, 'kallawaya/error404.html')


def edit_profile(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = EditProfileForm(request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                return redirect('/kallawaya/profile')
        else:
            form = EditProfileForm(instance=request.user)
            args = {'form': form}
            return render(request, 'kallawaya/edit_profile.html', args)
    else:
        return render(request, 'kallawaya/error404.html')


def change_password(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(data=request.POST, user=request.user)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                return redirect('/kallawaya/profile')
            else:
                return redirect('/kallawaya/change-password')
        else:
            form = PasswordChangeForm(user=request.user)
            args = {'form': form}
            return render(request, 'kallawaya/change_password.html', args)
    else:
        return render(request, 'kallawaya/error404.html')


def list_Plant(request):
    queryset = Plant.objects.all()
    context = {
        "object_list": queryset
    }
    return render(request, "kallawaya/plants.html", context)


def testHome(request):
    return render(request, 'kallawaya/testHome.html')


def contact(request):
    return render(request, 'kallawaya/contact.html')


def testInit(request, pk=None):

    if pk == None:
        molestias = Molestia.objects.all()
        return render(request, 'kallawaya/testInit.html', {'molestias': molestias})
    else:
        if pk:
            molestia = Molestia.objects.get(pk=pk)
        else:
            molestia = request.molestia
        args = {'molestia': molestia}
        return render(request, 'kallawaya/testFinal.html', args)


def herbario(request, pk=None):
    if pk == None:
        plants = Plant.objects.all()
        users = User.objects.all()
        return render(request, 'kallawaya/herbario.html', {'plants': plants})
    else:
        if pk:
            plant = Plant.objects.get(pk=pk)
        else:
            plant = request.plant
        args = {'plant': plant}
        return render(request, 'kallawaya/infoPlant.html', args)


class HomeView(TemplateView):
    template_name = 'kallawaya/testInit.html'

    def get(self, request):
        form = HomeFormInit()
        return render(request, self.template_name, {'form': form})


def herbario2(request, pk=None):
    if pk == None:
        plants = Plant.objects.all()
        return render(request, 'kallawaya/herbario2.html', {'plants': plants})
    else:
        if pk:
            plant = Plant.objects.get(pk=pk)
        else:
            plant = request.plant
        args = {'plant': plant}
        return render(request, 'kallawaya/infoPlant2.html', args)

appkallawaya/templates/kallawaya/change_password.html
{% extends 'base.html' %}
{% block head %}
<title>Change password</title>
{% endblock %}

{% block body %}
{% load static %}
<style>
    input{
     border-radius: 12px;
     background-color: #65dfef;
     padding-top: 8px;
     padding-left: 5px;
     margin-bottom: 40px;
     border: 2px solid #ffffff;
     background: transparent;
}
    label{
        color: #ffffff;
        font-size: 20px;
        padding-right: 30px;
    }
</style>
<body style="background-color:#0cdcab">
    <div class="container" style="margin-top: 140px; margin-left:160px;">
       <h1 style="color:#651dfd">Actualiza tu contraseña</h1>
       <img src="{% static 'kallawaya/img/new5.png' %}" align="right" style="margin-right:100px;">
        <h3 style="color: white">"El limón es un nutriente esencial para mantener una buena salud"</h3>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn_2" style="background-color: #651dfd; margin-left:200px;">Submit</button>
        </form>
        <a href="/kallawaya/profile" class="btn_2" style="background-color: #651dfd;  margin-top:-65px;">Atras</a>
    </div>

</body>

{% endblock %}

appkallawaya/templates/kallawaya/contact.html
{% extends 'base.html' %}
<h1>CONTACT</h1>
{% block head %}
    <title>Contact Page</title>
{% endblock %}

{% block body %}
    <!--::banner part start::-->
        {% load static %}
        <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg" style="background-color: #dd4f41">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <img src="{% static 'kallawaya/img/new6.png' %}">
                            <h2>CONTÁCTENOS</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

  <!-- ================ contact section start ================= -->
  <section class="contact-section section_padding">
    <div class="container">
      <div class="d-none d-sm-block mb-5 pb-4">

           <div class="row">
        <div class="col-12">
          <h2 class="contact-title">MÁNDANOS UN MENSAJE</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form" action="contact_process.php" method="post" id="contactForm"
            novalidate="novalidate">
            <div class="row">
              <div class="col-12">
                <div class="form-group">

                  <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Ingresa el mensaje'"
                    placeholder='Ingresa el mensaje'></textarea>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="name" id="name" type="text" onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter your name'" placeholder='Ingresa tu nombre'>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Ingresa tu mail'" placeholder='Ingresa tu mail'>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter Subject'" placeholder='Asunto'>
                </div>
              </div>
            </div>
            <div class="form-group mt-3">
              <button type="submit" class="button button-contactForm btn_1">Mandar mensaje <i class="flaticon-right-arrow"></i> </button>
            </div>
          </form>
        </div>
        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>La Paz Bolivia</h3>
              <p>Universidad Privada Boliviana</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>777-9888-88</h3>
              <p>Atención 24/7</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>info@kallawaya.org</h3>
              <p>Escríbenos</p>
            </div>
          </div>
        </div>
      </div><br><br>
      <div class="container" ">
        <h2>CONOCE AL EQUIPO</h2><br>
        <img src="{% static 'kallawaya/img/mari.png' %}" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static 'kallawaya/img/sara.png' %}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static 'kallawaya/img/emmi.png' %}"><br>
        <p> Mariana Carlo, Lead Developer &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sara Uriarte, Lead Developer &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Emmi Aguilar, Lead Developer</p>

    </div>
  </section>
  <!-- ================ contact section end ================= -->




{% endblock %}

appkallawaya/templates/kallawaya/error500.html
{% extends 'base.html' %}
<h1>HERBARIO</h1>
{% block head %}
    <title>error404</title>
{% endblock %}

{% block body %}
    <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg"  style="background-color: #ab1c53">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <br>
                            <br>
                            <img src="{% static 'kallawaya/img/error500.png' %}">
                            <h2>OOPS! NO ENCONTRAMOS LA PÁGINA</h2><br>
                            <a href="/kallawaya/login"><H2 style="color: #7ef2e5">VUELVE A INICIO (click aquí)</H2></a>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->
{% endblock %}

appkallawaya/templates/kallawaya/herbario.html
{% extends 'base.html' %}
<h1>HERBARIO</h1>
{% block head %}
    <title>Herbario</title>
{% endblock %}

{% block body %}
    <!--::banner part start::-->
        {% load static %}
     <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg"  style="background-color: #0cdcab">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <br>
                            <br>
                            <img src="{% static 'kallawaya/img/herbario2.png' %}">
                            <h2>HERBARIO</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
   
    <!-- breadcrumb start-->
    



        <div class="container">
            <div class="row">
                {% for instance in plants  %}
                <div class="col-sm">
                    <a href="{% url 'appkallawaya:herbario_picked' pk=instance.id %}"><h4 style="color: white"> <img src="{% static 'kallawaya/img/plus1.png' %}"> {{ instance.name }}</h4></a>
                </div>
                {% endfor %}
            </div>
        </div>
</section>
    <!--::footer_part start::-->
    <footer class="footer_part">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-4 col-lg-4">
                    <div class="single_footer_part">
                        <a href="index.html" class="footer_logo_iner"> <img src="{% static 'kallawaya/img/logo1.png' %}" alt="#"> </a>
                        
                    </div>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-2">
                    <div class="single_footer_part">
                       
                    </div>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-2">
                    <div class="single_footer_part">
                       
                    </div>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-2">
                    <div class="single_footer_part">
                        
                    </div>
                </div>
                <div class="col-sm-4 col-md-3 col-lg-2">
                    <div class="single_footer_part">
                        
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-lg-8">
                    <div class="copyright_text">
                        <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This page is made by Kallawaya.org
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
                    </div>
                </div>
                
            </div>
        </div>
    </footer>
    <!--::footer_part end::-->

  <!--::footer_part end::-->


    <!--::subscribe us part end::-->
{% endblock %}

appkallawaya/templates/kallawaya/herbario2.html
{% extends 'base.html' %}
<h1>HERBARIO</h1>
{% block head %}
    <title>Herbario</title>
{% endblock %}

{% block body %}
    <!--::banner part start::-->
        {% load static %}
     <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg"  style="background-color: #0cdcab">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <br>
                            <br>
                            <img src="{% static 'kallawaya/img/herbario2.png' %}">
                            <h2>HERBARIO</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
   
    <!-- breadcrumb start-->
    



        <div class="container">
            <div class="row">
                {% for instance in plants  %}
                <div class="col-sm">
                    <a href="{% url 'appkallawaya:herbario2_picked' pk=instance.id %}"><h4 style="color: white"> <img src="{% static 'kallawaya/img/plus1.png' %}"> {{ instance.name }}</h4></a>
                </div>
                {% endfor %}
            </div>
        </div>
</section>
    <!--::footer_part start::-->
    <footer class="footer_part">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-4 col-lg-4">
                    <div class="single_footer_part">
                        <a href="index.html" class="footer_logo_iner"> <img src="{% static 'kallawaya/img/logo1.png' %}" alt="#"> </a>
                        
                    </div>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-2">
                    <div class="single_footer_part">
                       
                    </div>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-2">
                    <div class="single_footer_part">
                       
                    </div>
                </div>
                <div class="col-sm-4 col-md-4 col-lg-2">
                    <div class="single_footer_part">
                        
                    </div>
                </div>
                <div class="col-sm-4 col-md-3 col-lg-2">
                    <div class="single_footer_part">
                        
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-lg-8">
                    <div class="copyright_text">
                        <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This page is made by Kallawaya.org
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
                    </div>
                </div>
                
            </div>
        </div>
    </footer>
    <!--::footer_part end::-->

  <!--::footer_part end::-->


    <!--::subscribe us part end::-->
{% endblock %}

appkallawaya/templates/kallawaya/home.html
{% extends 'base.html' %}
<h1>Home</h1>
{% block head %}
    <title>Home Page</title>
{% endblock %}

{% block body %}
    <!--::banner part start::-->
        {% load static %}
        <section class="banner_part" style="background-image: url('{% static 'kallawaya/img/banner_bg2.png' %}')">
            <div class="container">
                <div class="row align-items-center justify-content-between" style="width: 1400px;">
                    <div class="col-lg-5">
                        <div class="banner_img d-none d-lg-block">
                            <img src="{% static 'kallawaya/img/index.png' %}" alt="">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="banner_text">
                            <div class="banner_text_iner">
                                <h1>KALLAWAYA</h1>
                                <H6>TU ASISTENTE MÉDICO PERSONAL</H6>
                            </div>
                        </div>
                    </div>
                </div>

            <img src="{% static 'kallawaya/img/animate_icon/Ellipse_7.png' %}" alt="" class="feature_icon_1 custom-animation1">
            <img src="{% static 'kallawaya/img/animate_icon/Ellipse_8.png' %}" alt="" class="feature_icon_2 custom-animation2">
            <img src="{% static 'kallawaya/img/animate_icon/Ellipse_1.png' %}" alt="" class="feature_icon_3 custom-animation3">
            <img src="{% static 'kallawaya/img/animate_icon/Ellipse_2.png' %}" alt="" class="feature_icon_4 custom-animation4">
            <img src="{% static 'kallawaya/img/animate_icon/Ellipse_3.png' %}" alt="" class="feature_icon_5 custom-animation5">
            <img src="{% static 'kallawaya/img/animate_icon/Ellipse_4.png' %}" alt="" class="feature_icon_6 custom-animation6">
        </section>
        <!--::banner part start::-->

        <!--::about_us part start::-->
    <section class="about_us section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6 col-lg-5">
                    <div class="about_us_text">
                        <img src="{% static 'kallawaya/img/icon/Icon_1.png' %}" alt="">
                        <h2>Un poco de nosotras...
                            </h2>
                        <p>Somos un equipo de ingenieras que quieren ayudar<br>
                        	al entorno boliviano, gracias a la etnobotánica<br>
                        	Estos son antiguos remedios caseros para curar<br>
                        diferentes tipos de enfermedades y heridas</p>

                    </div>
                </div>
                <div class="col-md-6 col-lg-6">
                    <div class="learning_img">
                        <img src="{% static 'kallawaya/img/new2.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'kallawaya/img/animate_icon/Ellipse_4.png' %}" alt="" class="feature_icon_1 custom-animation1">
    </section>
    <!--::about_us part end::-->

    <!--::about_us part start::-->
    <section class="about_us right_time">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6 col-lg-6">
                    <div class="learning_img">
                        <img src="{% static 'kallawaya/img/about_img_1.png' %}" alt="">
                    </div>
                </div>
                <div class="col-md-6 col-lg-5">
                    <div class="about_us_text">
                        <img src="{% static 'kallawaya/img/icon/Icon_2.png' %}" alt="">
                        <h2>Asistente Médico 24 hrs</h2>
                        <p>Estamos las 24 horas al día, los 7 días a la semana.<br> Te brindamos una atención de calidad
                   y personalizada</p>

                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'kallawaya/img/animate_icon/Ellipse_5.png' %}" alt="" class="feature_icon_2 custom-animation2">
    </section>


    <br>
    <br>
    <br>
    <!--::subscribe us part end::-->
    <section class="subscribe_part padding_bottom">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="subscribe_part_text text-center">
                        <h2>Suscríbete para las mejores actualizaciones</h2>
                        <div class="subscribe_form">
                            <form action="#">
                                <div class="form-row">
                                    <div class="col-sm-9">
                                        <input type="email" class="form-control" placeholder="Ingresa tu mail">
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="subscribe_btn">
                                            <div class="btn_2 d-block" style="color: blue;">Suscribirse</div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <img src="{% static 'kallawaya/img/animate_icon/Ellipse_5.png' %}" alt="" class="feature_icon_2 custom-animation2">
    </section>
    <!--::subscribe us part end::-->
{% endblock %}

appkallawaya/templates/kallawaya/infoPlant.html
{% extends 'base.html' %}

{% block head %}
<title>HOLA</title>
{% endblock %}

{% block body %}
{% load static %}
     <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg"  style="background-color: #0cdcab">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <br>
                            <br>
                            <img src="{% static 'kallawaya/img/herbario2.png' %}">
                            <h2>HERBARIO</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<body style="background-color:#0cdcab">
<div class="container">
    </br>
       <img src="{% static 'kallawaya/img/icon.png' %}" align="left" style="margin-right:10px; margin-top: -10px;"><h1 style="color:#651dfd">{{ plant.name }}</h1>
    </br>
    <h2 style="color: white">Descripción:</h2>
       <img src="{% static 'kallawaya/img/new5.png' %}" align="right">
       <h4 style="color: white">
        {{ plant.description }}
        </h4>
        <br>
        <h2 style="color: white">Cura:</h2>
        <h4 style="color: white">
        {{ plant.cura }}
        </h4> <br>

        <br>
</div>
</body>
{% endblock %}

appkallawaya/templates/kallawaya/infoPlant2.html
{% extends 'base.html' %}

{% block head %}
<title>Descripcion</title>
{% endblock %}

{% block body %}
{% load static %}
     <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg"  style="background-color: #0cdcab">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <br>
                            <br>
                            <img src="{% static 'kallawaya/img/herbario2.png' %}">
                            <h2>HERBARIO</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<body style="background-color:#0cdcab">
<div class="container">
    </br>
       <img src="{% static 'kallawaya/img/icon.png' %}" align="left" style="margin-right:10px; margin-top: -10px;"><h1 style="color:#651dfd">{{ plant.name }}</h1>
    </br>
    <h2 style="color: white">Descripción:</h2>
       <img src="{% static 'kallawaya/img/new5.png' %}" align="right">
       <h4 style="color: white">
        {{ plant.description }}
        </h4>
        <br>
        <h2 style="color: white">Cura:</h2>
        <h4 style="color: white">
        {{ plant.cura }}
        </h4> <br>

        <br>
</div>
</body>
{% endblock %}